import setuptools

with open("README.md", "r", encoding="utf-8") as f:
    long_description = f.read()

__version__ = "0.1.0"
REPO_NAME = "AI-Text-Generation-Detection-MLOps"
AUTHOR_USER_NAME = "Mohamed Stifi"
AUTHOR_EMAIL = "mohamed.stifi.stifi@gmail.com"
PROJECT_NAME = "text_classifier"

REPO_DESCRIPTION = '\n'.join([
    "An MLOps-enabled project for detecting whether a given text is written by a human or generated by AI. ",
    "Includes modular pipelines for data preprocessing, model training, evaluation, inference, and deployment. ",
    "Built with PyTorch, PyTorch Lightning, MLflow, Hydra, and FastAPI."
])

setuptools.setup(
    name=PROJECT_NAME,
    version=__version__,
    author=AUTHOR_USER_NAME,
    author_email=AUTHOR_EMAIL,
    description=REPO_DESCRIPTION,
    long_description=long_description,
    #long_description_content="text/markdown",
    url=f"https://github.com/{AUTHOR_USER_NAME}/{REPO_NAME}",
    project_urls={
        "Bug Tracker": f"https://github.com/{AUTHOR_USER_NAME}/{REPO_NAME}/issues",
    },
    package_dir={"": "src"},
    packages=setuptools.find_packages(where="src"),

)